//
// Created by 86189 on 2024/3/31.
//
#include "GIMBAL.h"
#include "UART.h"
#include "define.h"
#include "can.h"
#include "MOTOR.h"
#include "TOP.h"
#include "main.h"

YUN_TYPEDEF_MOTOR_ YUN_V_GIMBAL[2]={0};
//YUN_TYPEDEF_MOTOR_ YUN_V_GIMBAL_YAW;
YUN_TYPEDEF_TOP TEST_2{ };
void GIMBAL_CAL(TYPEDEF_DBUS *dbus_data,YUN_TYPEDEF_MOTOR_ *YUN_V_GIMBAL)
{

    YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_YAW].DATA.AIM += dbus_data->REMOTE.CH0_int16 * 0.001f;
    YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_PIT].DATA.AIM += dbus_data->REMOTE.CH2_int16 * 0.001f;

    if( YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_PIT].DATA.AIM > 5200)
    {
        printf("yaw aim limit ok");
        YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_PIT].DATA.AIM = 5200;
    }
    if(YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_PIT].DATA.AIM < 1800)
    {
        YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_PIT].DATA.AIM = 1800;
    }
    YUN_F_MOTOR_PID_GIMBAL(&YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_YAW], YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_YAW].DATA.ANGLE_NOW, YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_YAW].DATA.SPEED_NOW);
    YUN_F_MOTOR_PID_GIMBAL(&YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_PIT], YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_PIT].DATA.ANGLE_NOW, YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_PIT].DATA.SPEED_NOW);

}

[[noreturn]] void YUN_F_GIMBAL_THREAD(TYPEDEF_DBUS *YUN_V_DBUS,YUN_TYPEDEF_MOTOR_ *YUN_V_GIMBAL)
{
//    YUN_F_MOTOR_CLEAR(&YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_YAW],YUN_D_MOTOR_GIMBAL_YAW);
//    YUN_F_MOTOR_CLEAR(&YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_PIT],YUN_D_MOTOR_GIMBAL_PIT);

    YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_PIT].PID_P.IN.P = 5;
    YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_PIT].PID_P.IN.I = 0.0001f;
    YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_PIT].PID_S.IN.P = 20;
    YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_PIT].DATA.AIM = 3400 ;
    YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_PIT].PID_P.IN.ALL_LIT = 2000;
    YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_PIT].PID_S.IN.ALL_LIT = 2000;
    YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_PIT].PID_P.IN.I_LIT = 8000;


    YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_YAW].PID_P.IN.P = 8.1f;
    YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_YAW].PID_P.IN.I = 0.0001f;
    YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_YAW].PID_P.IN.ALL_LIT = 8000;
    YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_YAW].PID_S.IN.P = 0.0f;
    YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_YAW].PID_S.IN.ALL_LIT = 5000;
    YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_YAW].PID_P.IN.I_LIT = 1000;

//    printf("kp: %f\n",YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_YAW].PID_P.IN.P);
//    YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_YAW].DATA.AIM = 3400 ;
    while(1){

        YUN_F_CAN_RECEIVE(YUN_V_GIMBAL,&TEST_2,YUN_D_CAN_2);
//        printf("%d\n",YUN_V_GIMBAL[0].DATA.ANGLE_NOW);
//        printf("YAW:%d\n PITCH:%d\n",YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_YAW].PID_P.out.ALL_OUT,YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_PIT].PID_P.out.ALL_OUT);

        GIMBAL_CAL(YUN_V_DBUS,YUN_V_GIMBAL);

        printf("YAW:%f PITCH:%f\n",YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_YAW].PID_P.out.ALL_OUT,YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_PIT].PID_P.out.ALL_OUT);
//        YUN_F_CAN_SEND(YUN_D_CAN_2, 0X2FF,YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_YAW].PID_P.out.ALL_OUT,0,YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_YAW].PID_P.out.ALL_OUT,0);
//        YUN_F_CAN_SEND(YUN_D_CAN_2, 0X2FF,0,0,YUN_V_GIMBAL[YUN_D_MOTOR_GIMBAL_YAW].PID_S.out.ALL_OUT,0);
        usleep(1);
    }

}